
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  port: 3306
  host: db

development:
  <<: *default
  host: db
  database: api_development
  password: password

test:
  <<: *default
  host: db
  database: api_test
  password: password

production:
  primary: &primary_production
    <<: *default
    database: api_production
    username: api
    password: <%= ENV["API_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: api_production_queue
    migrations_paths: db/queue_migrate
